### PR TITLE
check for macOS

### PR DESCRIPTION
**Pull request by JayBrown**
ditto

PS: any more files with `sha256sum` in them?

### CODE REVIEW

**Comment by JayBrown** [comment]
There's also the issue with `wget`. That program is not part of macOS by default, only `curl`. I have it installed using Homebrew, but maybe the `wget` line(s) should also go in the `else` part (non-macOS), and a `curl` variant into the `Mac` part of the iffi.

**Comment by Doc73** [comment]
Yes, I know! But I'm not a Mac user. Therefore, all suggestios are welcome. Many thanks! :-)

**Comment by JayBrown** [comment]
One thing maybe: according to the BSD man page, the `ar` program is executed like `ar -x` on macOS (and BSD), and in the script it's `ar x`. I'd have to test it all, probably even step by step, to see if there are any problems on macOS. (Tomorrow at the earliest.)

**Comment by JayBrown** [comment]
The `curl` variant for macOS would be (for example)

`curl -L -o $(DEPDIR)/gcide/dict-gcide_$(GCIDEVERSION)_all.deb http://http.debian.net/debian/pool/main/d/dict-gcide/dict-gcide_$(GCIDEVERSION)_all.deb`

The `-L` option is necessary for redirects; `wget` seems to follow redirects automatically. Small `-o` instead of `-O`.

(Still don't know about the variables using single parentheses.)

**Comment by JayBrown** [comment]
Found something out: The form `$(VARIABLE)` with single parentheses seems to be relevant to GNU `make`. For BSD/POSIX `make` it might only work with `${VARIABLE}`. But I'd have to test everything first before we change anything.

**Comment by nickjwhite** [comment]
Hi @JayBrown, thanks for taking a look at this, I'll go through each point you made here.

In makefiles $(VAR) and ${VAR} are treated the same, it's just a case of style, as per the OpenGroup specs; see http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html#tag_20_76_13_05 So, all should be well there and things can stay as is.

As to replacing wget with curl to make things easier for OSX users, sure, sounds good to me, thanks for the suggestion.

As to the difference in <code>ar</code> usage between the BSDs and Linux, thanks for pointing that out, I never knew about that. The GNU ar utility that's standard on Linux works perfectly fine with the <code>ar -x</code> usage too, so switching to that everywhere seems very sensible to me.

@JayBrown and @Doc73, do either of you fancy working up some new patches for these? No worries if not, I can always do it myself, but if you do, send in a pull request and I'll be very happy accept it.

**Pull request merged**
